import type { CollectionInfo, Draft07DefinitionProperty, MarkdownRoot } from '@nuxt/content'
import type { DatabaseItem } from 'nuxt-studio/app'
import type { MinimarkNode, MinimarkTree } from 'minimark'
import { visit as minimarkVisit } from 'minimark'

export function sanitizeDocumentTree(document: DatabaseItem, collection: CollectionInfo) {
  if (!document.body && (document.meta?.body as unknown as MinimarkTree)?.type === 'minimark') {
    document.body = (document.meta?.body as unknown as MinimarkTree)
    Reflect.deleteProperty(document.meta, 'body')
  }

  if ((document.body as unknown as MinimarkTree)?.type === 'minimark') {
    document.body = removeLastStylesFromTree(document.body as MarkdownRoot)

    // remove the codeblock token and convert highlighted code blocks to plain code blocks
    minimarkVisit(document.body as MinimarkTree, (node: MinimarkNode) => node[0] === 'pre', (node: MinimarkNode) => {
      const tag = node[0]
      const props = node[1] as Record<string, unknown>

      if ((props as Record<string, unknown> || {}).code) {
        // TODO: We need to make sure that there is no custom class
        Reflect.deleteProperty(props, 'className')
        return [
          tag,
          {
            ...(props || {}),
            style: props.style || undefined,
            meta: props.meta || undefined,
          },
          [
            'code',
            { __ignoreMap: '' },
            (props as Record<string, unknown> || {}).code,
          ],
        ]
      }
      return node
    })
  }

  /**
   * Remvoe editor's hidden keys from the document
   * Studio assumes that hidden fields are auto-generated by modules or user hooks
   * Unfortunately, there is no way to re-calculate these fields in production because hooks live in module scope
   * These fields will generate once changes are committed to the repository
   */
  if (collection?.schema?.definitions?.[collection.name]?.properties) {
    const properties = collection?.schema?.definitions?.[collection.name]?.properties as Record<string, Draft07DefinitionProperty> | undefined
    const hiddenKeys = Object.keys(properties || {})
      .filter(key => properties?.[key]?.$content?.editor?.hidden)

    for (const key of hiddenKeys) {
      Reflect.deleteProperty(document, key)
    }
  }

  return document
}

export function removeLastStylesFromTree(body: MarkdownRoot) {
  if (body.value[body.value.length - 1]?.[0] === 'style') {
    return { ...body, value: body.value.slice(0, -1) }
  }
  return body
}
